### ISSUE TITLE
Replace manually created EDGE router with more standardized solution

### ISSUE THREAD

**Issue by kirillmakhonin** [legion-platform/legion#859]
We have to replace our EDGE (that is OpenResty + python code) with istio
 
Tasks:
- [ ] Istio deployment
- [ ] Rename `model-id` with `model-name`
- [ ] Remove edge deployment
- [ ] Legion operator supports istio
- [ ] Remove templater 

Subtasks:
- #101 - Reduce count of HTTP proxies during model API invocation
- #904 - Creating deployment with same image as exist does not work 
- #14 - Split (A/B) testing
- #207 - Set up explicit timeouts for model API

**Comment by kirillmakhonin** [comment]
Also we need to update JupyterLab plugin to support new API
