### ISSUE TITLE
Legion deployment to AKS

### ISSUE THREAD

**Issue by alexander-semenets** [legion-platform/legion#981]
As A DevOps engineer I'd like to have terraform modules for Legion deployment to AKS cluster.
This also requires Legion Robot tests modification if needed.

UPD (2019-11-10):
Major subtasks:
- [x] Add Terraform module to deploy Azure cloud-specific prerequisites 
- [x] Add Azure Blob storage type to legion-operator and fluentd (PoC)
- [x] Achieve a successful deploy of Legion helm chart to AKS cluster without errors
- [x] Add/rewrite Robot framework tests to check Legion integrity with Azure services
- [x] We have to rewrite packaging workflow (@mcdoker18 has some thoughts/plans on this)

Further subtasks with minor priority (marked as done and separated to specific issues):
- [x] Add the ability to perform all storage operations using single auth method (Storage Account Name + Storage Account Key; SAS Token; specially created Azure service account (Service Principal)) - TBD in #1031
- [x] Restrict k8s master API endpoint access - TBD in #1044
- [x] Deal with the incorrect behavior of network security groups when using multiple node pools - TBD in #1045
